apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-veiculo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-veiculo
  template:
    metadata:
      labels:
        app: api-veiculo
    spec:
      containers:
      - name: api-veiculo
        image: api_veiculo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: api-veiculo-service
spec:
  selector:
    app: api-veiculo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
