name: Cliente WebFlux Kubernetes Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'cliente-webflux/**'

env:
  DOCKER_REGISTRY: matias_reinke.azurecr.io
  KUBERNETES_NAMESPACE: default 
  DEPLOYMENT_NAME: cliente-webflux-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests --file cliente-webflux/pom.xml
        
    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_REGISTRY }}/cliente-webflux:${{ github.sha }} ./cliente-webflux
        
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Push image to Docker Registry
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/cliente-webflux:${{ github.sha }}
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=./kubeconfig
        
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} cliente-webflux=${{ env.DOCKER_REGISTRY }}/cliente-webflux:${{ github.sha }} -n ${{ env.KUBERNETES_NAMESPACE }}
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.KUBERNETES_NAMESPACE }}
