name: Main Workflow

on:
  push:
    paths:
      - 'cliente-webflux/**'
  pull_request:
    paths:
      - 'cliente-webflux/**'

jobs:
  cliente-webflux:
    uses: ./cliente-webflux/.github/workflows/cliente-webflux-ci.yml@main
